// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcgyuifqawsqakqpexny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZ3l1aWZxYXdzcWFrcXBleG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODQ0NjksImV4cCI6MjA2ODk2MDQ2OX0.GNkVQfiZ_ZYjO9h6snccW6KTbQkm_T45aRGMeDrBDm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});